DELETE FROM HAS_PET hp WHERE ID = 3

INSERT INTO HAS_PET hp 
VALUES(1, '기타');

INSERT INTO HAS_PET hp 
VALUES(2, '강아지');

INSERT INTO HAS_PET hp 
VALUES(3, '고양이');

INSERT INTO BOARD_CATEGORY bc 
VALUES(1, '일상');
INSERT INTO BOARD_CATEGORY bc 
VALUES(2, '질문');
INSERT INTO BOARD_CATEGORY bc 
VALUES(3, '나만의 팁');

INSERT INTO MARKET_CATEGORY mc 
VALUES(1, '식품');
INSERT INTO MARKET_CATEGORY mc 
VALUES(2, '장난감');
INSERT INTO MARKET_CATEGORY mc 
VALUES(3, '용품');
INSERT INTO MARKET_CATEGORY mc 
VALUES(4, '기타');
