DELETE FROM HAS_PET hp WHERE ID = 3

INSERT INTO HAS_PET hp 
VALUES(1, '기타');

INSERT INTO HAS_PET hp 
VALUES(2, '강아지');

INSERT INTO HAS_PET hp 
VALUES(3, '고양이');

INSERT INTO BOARD_CATEGORY bc 
VALUES(1, '일상');
INSERT INTO BOARD_CATEGORY bc 
VALUES(2, '질문');
INSERT INTO BOARD_CATEGORY bc 
VALUES(3, '나만의 팁');

INSERT INTO MARKET_CATEGORY mc 
VALUES(1, '식품');
INSERT INTO MARKET_CATEGORY mc 
VALUES(2, '장난감');
INSERT INTO MARKET_CATEGORY mc 
VALUES(3, '용품');
INSERT INTO MARKET_CATEGORY mc 
VALUES(4, '기타');

SELECT * FROM CUSTOMER_ANNOUNCEMENT ca 

ALTER TABLE CUSTOMER_ANNOUNCEMENT MODIFY CONTENT VARCHAR2(1000)

SELECT
	cq.CONO ,
	cq.TITLE ,
	cq.QUESTION,
	cq.QUESTION_MEMBER_MEMBER_ID ,
	ar.TEXT,
	(
	SELECT
		m.NICK_NAME
	FROM
		CUSTOMER_QUESTION cq
	JOIN "MEMBER" m ON
		cq.QUESTION_MEMBER_MEMBER_ID = m.MEMBER_ID) AS QMemberinfo,
	ar.ADMIN_REPLYER_MEMBER_ID
FROM
	CUSTOMER_QUESTION cq
JOIN ADMIN_REPLY ar ON
	cq.CONO = ar.CUSTOMER_QUESTION_CONO;
	
DELETE FROM CUSTOMER_ANNOUNCEMENT ca WHERE ADMIN_MEMBER_MEMBER_ID=8;

DELETE FROM CUSTOMER_QUESTION cq WHERE QUESTION_MEMBER_MEMBER_ID = 9;
DELETE FROM ADMIN_REPLY ar WHERE ADMIN_REPLYER_MEMBER_ID = 8;
DELETE FROM "MEMBER" m WHERE MEmber_id = 13;