-- EMPLOYESS (scott 계정의 emp 테이블 원본)
-- EMPLOYESS 전체 조회
SELECT * FROM EMPLOYEES e;

-- EMPLOYESS 의 first_name, last_name, job_id 조회
SELECT
	FIRST_NAME,
	LAST_NAME,
	JOB_ID
FROM
	EMPLOYEES e;

--사원번호가 176인 사원의 LAST_NAME, 부서번호 조회
SELECT LAST_NAME, DEPARTMENT_ID, EMPLOYEE_ID FROM EMPLOYEES e WHERE EMPLOYEE_ID = 176;


--연봉이 12000 이상 되는 직원들의 LAST_NAME 과 연봉 조회
SELECT LAST_NAME, SALARY FROM EMPLOYEES e WHERE SALARY >= 12000;


--연봉이 5000 에서 12000 범위가 아닌 사람들의 LAST_NAME 과 연봉
SELECT LAST_NAME, SALARY FROM EMPLOYEES e WHERE SALARY < 5000 OR SALARY >12000

--20번 혹은 50번 부서에서 근무하는 사원들의 LAST_NAME, 부서번호를 조회
--단 이름의 오름차순, 부서의 오름차순으로 정렬
SELECT
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (50, 20)
ORDER BY
	LAST_NAME ASC,
	DEPARTMENT_ID ASC ;


--커미션을 버는 사원들의 LAST_NAME, SALARY, COMMISSION_PCT를 조회
--단 연봉의 내림차순, 커미션 내림차순으로 정렬
SELECT
	LAST_NAME,
	SALARY,
	COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT != 0
ORDER BY
	SALARY DESC,
	COMMISSION_PCT DESC;


--연봉이 2500,3500,7000이 아니며 JOB_ID가 SA_REP OR ST_SLERK인 사원 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	SALARY NOT IN (2500, 3500, 7000) AND 
	JOB_ID IN('SA_REP', 'ST_SLERK');
	

--2018/02/20~2018/05/01 사이에 고용된 직원들의 LAST_NAME,사번,고용일자(HIRE) 조회
SELECT
	LAST_NAME ,
	EMPLOYEE_ID ,
	HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	HIRE_DATE >= '2018-02-20'
	AND HIRE_DATE <= '2018-05-01';


--2015년에 고용된 사원 조회
SELECT *
FROM EMPLOYEES e 
WHERE HIRE_DATE >= '2015-01-01' AND HIRE_DATE <= '2015-12-31';

--20번 혹은 50번 부서에서 근무하며, 연봉이 5000 ~ 12000 사이인 직원들의 FIRST_NAME, LAST_NAME, 연봉조회(연봉 오름차순)
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES e WHERE DEPARTMENT_ID IN (20,50) AND SALARY BETWEEN 5000 AND 12000 ORDER BY SALARY ASC ;

--연봉 5000~12000사이가 아닌 직원들의 정보 조회
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES e WHERE SALARY NOT BETWEEN 5000 AND 12000;

--2018/02/20~2018/05/01 사이에 고용된 직원들의 LAST_NAME,사번,고용일자(HIRE) 조회
SELECT LAST_NAME ,EMPLOYEE_ID ,HIRE_DATE
FROM EMPLOYEES e
WHERE HIRE_DATE BETWEEN '2018-02-20' AND '2018-05-01';


--LIKE
--LAST_NAME 에 U 가 포함되는 사원들의 사번, LAST_NAME 조회
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%u%';

--LAST_NAME 에 네번째 글자가 A 인 사원들의 사번, LAST_NAME 조회
SELECT EMPLOYEE_ID, LAST_NAME 
FROM EMPLOYEES e
WHERE LAST_NAME LIKE '___a%';

--LAST_NAME 에 A 혹은 E 글자가 포함되는 사원들의 사번, LAST_NAME 조회(단, LAST_NAME 오름차순)
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME DESC;

--LAST_NAME 에 A 와 E 글자가 포함되는 사원들의 사번, LAST_NAME 조회(단, LAST_NAME 오름차순)
SELECT EMPLOYEE_ID , LAST_NAME 
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%a%' AND LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME DESC;

--IS NULL
--MANAGER ID 가 NULL 인 사원들의 LAST_NAME 및 JOB_ID 조회
SELECT LAST_NAME, JOB_ID FROM EMPLOYEES e WHERE e.MANAGER_ID IS NULL;

--JOB_ID가 ST_CLERK가 아닌 사원이 없는 부서 조회
--단, 부서 번호가 NULL인 경우는 제외한다.
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES e WHERE JOB_ID != 'ST_CLERK' AND e.DEPARTMENT_ID IS NOT NULL;

--COMMISSION_PCT가 NULL이 아닌 사원들 중에서 COMMISSION = SALARY *  COMMISSION_PCT를 구한다
-- 사원번호, FIRST_NAME, JOB_ID 와 함께 조회
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY, COMMISSION_PCT, SALARY * COMMISSION_PCT AS COMMISION FROM EMPLOYEES e WHERE COMMISSION_PCT IS NOT NULL;